name: GitHub Action CI
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    container: udzura/mruby-build-base:0.1.1
    steps:
      - uses: actions/checkout@v1
      - name: Build binary
        env:
          MRUBY_VERSION: master
        run: |
          rake
      - name: Run tests
        env:
          MRUBY_VERSION: master
        run: |
          rake test
      - uses: actions/upload-artifact@master
        with:
          name: bt2prom
          path: mruby/bin/bt2prom