name: Hello CI
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@master
        with:
          version: 2.6.x
      - name: setup rake
        run: |
          gem install rake
      - name: build
        env:
          MRUBY_VERSION: master
        run: |
          rake
      - name: test
        env:
          MRUBY_VERSION: master
        run: |
          rake test