name: Hello CI
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
      - name: build
        env:
          MRUBY_VERSION: master
        run: |
          rake
      - name: test
        env:
          MRUBY_VERSION: master
        run: |
          rake test